---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: home-ops
  labels:
    app.kubernetes.io/name: stirling-pdf
    app.kubernetes.io/part-of: homelab-ops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: stirling-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: frooodle/s-pdf:latest
          env:
            - name: SECURITY_ENABLELOGIN
              value: "false"
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: "false" # save ram and space
            - name: SYSTEM_DEFAULT_LOCALE
              value: "en-US"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "4000m"
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: home-ops
spec:
  selector:
    app.kubernetes.io/name: stirling-pdf
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf
  namespace: home-ops
  annotations:
    tailscale.com/tags: "tag:k8s"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - pdf-tools
  rules:
    - host: pdf-tools
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf
                port:
                  number: 8080
