apiVersion: v1
kind: Service
metadata:
  name: argocd-server-tailscale
  namespace: argocd
  annotations:
    tailscale.com/hostname: "argocd-ops"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
