apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: net-utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: net-utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
