apiVersion: v1
kind: Namespace
metadata:
  name: storage-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-scratch
  namespace: storage-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-scratch-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints", "persistentvolumes", "pods"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-scratch-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-scratch-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-scratch
    namespace: storage-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config-scratch
  namespace: storage-system
data:
  config.json: |-
    {
      "nodePathMap":[
      {
        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
        "paths":["/mnt/scratch"]
      }
      ]
    }
  setup: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    mkdir -m 0777 -p ${absolutePath}
  teardown: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    rm -rf ${absolutePath}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner-scratch
  namespace: storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner-scratch
  template:
    metadata:
      labels:
        app: local-path-provisioner-scratch
    spec:
      serviceAccountName: local-path-provisioner-scratch
      containers:
        - name: local-path-provisioner-scratch
          image: rancher/local-path-provisioner:v0.0.30
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --service-account-name
            - local-path-provisioner-scratch
            - --provisioner-name
            - cluster.local/scratch-path-provisioner
            - --helper-image
            - rancher/library-busybox:1.36.1
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config-scratch
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scratch
provisioner: cluster.local/scratch-path-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
