apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://pkgs.tailscale.com/helmcharts"
    chart: "tailscale-operator"
    targetRevision: "1.78.1" # Pin a version for stability
    helm:
      values: |
        oauth:
          secretName: operator-oauth
          clientIdKey: kikfrMEvEA21CNTRL 
          clientSecretKey: tskey-auth-kikfrMEvEA21CNTRL-nxhdDTPSxiEL2Zi65dHPjEjrX7ttA1yv
        # We enforce the operator to watch all namespaces so we can use it everywhere
        operatorConfig:
          hostname: "k8s-operator"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
